name: Build container image (Azure Resource Manager)
on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Log in to docker.io
        uses: redhat-actions/podman-login@v1.6
        with:
          username: "clincha"
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: docker.io

      - name: Push image
        run: make container-push-azrm