name: Build container images
on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    strategy:
      matrix:
        container:
          - terraform-provider-proxmox
          - terraform-provider-proxmox-azrm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: redhat-actions/podman-login@v1.6
        with:
          username: "clincha"
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: docker.io

      - name: ${{ matrix.container }} build and push
        run: make push-terraform-provider-proxmox \
          CONTAINER_NAME=${{ matrix.container }}